apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - vault-serviceaccount.yaml
  - vault-deployment.yaml
  - vault-service.yaml
  - vault-configmap.yaml

commonLabels:
  app.kubernetes.io/name: vault
  app.kubernetes.io/component: infrastructure
  app.kubernetes.io/part-of: argocd-learn
