tunnel: cloudflared
credentials-file: /etc/cloudflared/creds/token
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
  - hostname: argocd.opt-5050-01.azhe.my.id
    service: https://argocd-server.argocd.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
  - hostname: portainer.argocd-learn.azhe.my.id
    service: https://portainer.portainer.svc.cluster.local:9443
    originRequest:
      noTLSVerify: true
  - hostname: dev-dotnet-app.argocd-learn.azhe.my.id
    service: http://develop-dotnet-app.argocd-learn.svc.cluster.local:80
  - hostname: dev-golang-app.argocd-learn.azhe.my.id
    service: http://develop-golang-app.argocd-learn.svc.cluster.local:80
  - hostname: dev-nodejs-app.argocd-learn.azhe.my.id
    service: http://develop-nodejs-app.argocd-learn.svc.cluster.local:80
  - hostname: golang-app.argocd-learn.azhe.my.id
    service: http://production-golang-app.argocd-learn.svc.cluster.local:80
  - hostname: nodejs-app.argocd-learn.azhe.my.id
    service: http://production-nodejs-app.argocd-learn.svc.cluster.local:80
  - hostname: dev-auth.corp.azhe.my.id
    service: http://keycloak.keycloak-dev.svc.cluster.local:80
  - hostname: stg-auth.corp.azhe.my.id
    service: http://keycloak.keycloak-stg.svc.cluster.local:80
  - hostname: vault.argocd-learn.azhe.my.id
    service: http://vault.vault.svc.cluster.local:8200
  - hostname: auth.corp.azhe.my.id
    service: http://keycloak.keycloak.svc.cluster.local:80
  - service: http_status:404
