apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    # Best practice is to use a config file for ingress rules
    # and other settings.
    # For now, we'll keep it simple as the original pod was just running the tunnel.
    tunnel: cloudflared
    credentials-file: /etc/cloudflared/creds/token
    metrics: 0.0.0.0:2000
    no-autoupdate: true
