apiVersion: v1
kind: Service
metadata:
  name: zizibot-engine
spec:
  selector:
    app: zizibot-engine
  ports:
    - port: 80
      targetPort: 7120
      protocol: TCP
      name: http
  type: ClusterIP
