apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Business Applications
  sourceRepos:
    - "*"
  destinations:
    - namespace: "argocd-learn"
      server: https://kubernetes.default.svc
    - namespace: "keycloak"
      server: https://kubernetes.default.svc
    - namespace: "keycloak-*"
      server: https://kubernetes.default.svc
    - namespace: "vault"
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "*"
      kind: "*"
